### ISSUE TITLE
Admin: Product links are null

### ISSUE THREAD

**Issue by daniellelecomte** [mediabeastnz/craft-commerce-back-in-stock#40]
### Describe the bug

When viewing back in stock log in the control panel, all of the product links are null:

`/admin/back-in-stock/null`

### Steps to reproduce

1. Log into Craft and navigate to the Back in Stock Logs
2. Attempt to click on any product name

### Craft CMS version

5.8.8

### Plugin version

4.0.8

### Multi-site?

No

**Comment by engram-design** [comment]
Seems to be okay on my end. Is the product or variant disabled, or a draft? Or what about multi-store?

**Comment by daniellelecomte** [comment]
Hi Josh! The few that I spot checked have the product and variant enabled, but the variant has a stock level of 0. No multi-store.

**Comment by engram-design** [comment]
Strange, I've been testing a few different scenarios, but the only time that should happen is if the product or variant can't actually be found. If nothing else, I've updated the handling of this to just exclude the link, rather than show something invalid like you were seeing.

Fixed for the next release. To get this early, run `composer require verbb/back-in-stock:"dev-craft-5 as 4.0.8"`.

**Comment by daniellelecomte** [comment]
Yeah this is strange and not ideal to remove the link if the product/variant exists. I just upgraded this site from 4 to 5... any chance that could have been a factor?

**Comment by engram-design** [comment]
I can't imagine it would be, but I'm still looking into it. 

Like I mentioned, if the variant can't be found, it won't output a link anymore (instead of `/admin/back-in-stock/null`) just in any case. But if there's something else going on with being able to find the variant/product on your project, that isn't happening on mine - that's what I'm still looking into. But at this stage, I can't seem to determine how under normal circumstances our plugin wouldn't be able to find a variant that does exist on your end.

**Comment by daniellelecomte** [comment]
Hi Josh - recently updated to the latest version and I still get a null link. Does that mean it finds a variant but can't seem to link to it for some reason?

**Comment by engram-design** [comment]
Yeah, something [here](https://github.com/verbb/back-in-stock/blob/f7856ab1d7ab5538a8c9d6c453dacd0547717dd3/src/controllers/LogsController.php#L99) must be not returning a `cpEditUrl` for the variant.

I suppose _technically_ it should be `$variant->getCpEditUrl()` but I don't think that'd make a difference.

**Comment by icreatestuff** [comment]
I'm also seeing this behaviour in version 4.1.0, Craft v5.9.20.

I see a link, with the correct variant name listed as the link text, but the URL is to /control/back-in-stock/null where `control` is my backend admin trigger location

**Comment by daniellelecomte** [comment]
Still happening for me as well on 4.1.0 and Craft 5.9.14.

**Comment by engram-design** [comment]
Just pushed a few more fixes to this for the next release. 

To get this early, run `composer require verbb/back-in-stock:"dev-craft-5 as 4.1.0"`

**Comment by daniellelecomte** [comment]
Thanks Josh - works perfectly now!

**Comment by engram-design** [comment]
Updated in [4.1.1](https://github.com/verbb/back-in-stock/releases/tag/4.1.1).
